name: Go tests with NeuVector allinone

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.2.0'
      - run: go version

      - name: Run the NeuVector allinone instance and Go unitary tests
        run: |
          make test
