name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.2.0'
      - run: go version

      - name: Run the NeuVector allinone instance
        run: |
          docker-compose down -v
          make neuvector

      - name: Waitings for NeuVector to initialize
        run: |
          sleep 30

      - name: Run the NeuVector allinone instance and Go unitary tests
        run: |
          make test
